CREATE TRIGGER updateLecType

AFTER UPDATE

ON DBM_PROJECT_v1'.'FAC MEMBER

FOR EACH ROW

BEGIN

IF NEW.LecType IS NULL

THEN DELETE FROM DBM_PROJECT_v1.RES_ASSIST WHERE RES_ASSIST.PersonID = (OLD.PersonID); 
DELETE FROM DBM_PROJECT_v1.ASSIST_PROF WHERE ASSIST_PROF.PersonID = (OLD.PersonID); 
DELETE FROM DBM_PROJECT_v1.ASSOC_PROF WHERE ASSOC_PROF.PersonID = (OLD.PersonID); 
DELETE FROM DBM PROJECT_v1.PROFFESOR WHERE PROFFESOR.PersonID =  (OLD.PersonID);
DELETE FROM DBM_PROJECT_v1.INSTRUCTOR WHERE INSTRUCTOR. InstID = (OLD.PersonID);

END IF;

IF NEW. LecType = 1
	THEN INSERT INTO DBM PROJECT_v1.'RES_ASSIST' ('PersonID') VALUES (NEW.PersonID);

END IF;

IF NEW. LecType = 2

IF NOT EXIST (SELECT FROM 'DBM_PROJECT_v1'.'INSTRUCTOR' WHERE INSTRUCTOR.InstID) 
	THEN INSERT INTO DBM_PROJECT_v1.INSTRUCTOR (InstID) VALUES (NEW.PersonID); 
	THEN INSERT INTO DBM_PROJECT_v1.ASSIST PROF (`PersonID`) VALUES (NEW.PersonID); 
	DELETE FROM DBM_PROJECT_v1.RES_ASSIST WHERE RES_ASSIST.PersonID = (OLD.PersonID);

END IF;

IF NEW. LecType = 3

	THEN INSERT INTO DBM_PROJECT_v1.ASSOC_PROF (`PersonID`) VALUES (NEW.PersonID); 
	DELETE FROM DBM_PROJECT_v1.ASSIST PROF WHERE ASSIST_PROF.PersonID = (OLD.PersonID);

END IF;

IF NEW. LecType = 4
	THEN INSERT INTO DBM_PROJECT_v1.PROFFESOR (PersonID) VALUES (NEW.PersonID); 
	DELETE FROM DBM_PROJECT_v1.ASSOC_PROF WHERE ASSOC_PROF.PersonID = (OLD.PersonID);

END IF;

IF NEW. LecType = 0

THEN INSERT INTO DBM_PROJECT_v1. INSTRUCTOR (InstID) VALUES (NEW.PersonID); 
	DELETE FROM DBM_PROJECT_v1.RES_ASSIST WHERE RES_ASSIST.PersonID = (OLD.PersonID); 
	DELETE FROM DBM_PROJECT_v1. ASSIST PROF WHERE ASSIST PROF. PersonID = (OLD.PersonID); 		DELETE FROM DBM_PROJECT_v1. ASSOC_PROF WHERE ASSOC_PROF.PersonID = (OLD.PersonID);       		DELETE FROM DBM_PROJECT_v1. PROFFESOR WHERE PROFFESOR. PersonID = (OLD.PersonID);

END IF;
END;
















CREATE TRIGGER `updateCoType`

AFTER UPDATE

ON DBM_PROJECT_v1. COURSE

FOR EACH ROW

BEGIN

IF NEW.CoType IS NULL
	THEN DELETE FROM DBM_PROJECT_v1.MANDATORY WHERE MANDATORY. CoCode = (OLD.CoCode); 
	DELETE FROM DBM_PROJECT_v1.TECHNICAL WHERE TECHNICAL. CoCode = (OLD.CoCode); 
	DELETE FROM DBM_PROJECT_v1.N TECHNICAL WHERE N_TECHNICAL.CoCode = (OLD.CoCode); 
	DELETE FROM DBM_PROJECT_v1.OPTIONAL WHERE OPTIONAL. CoCode = (OLD.CoCode);

END IF;

IF NEW.CoType = 1

THEN INSERT INTO DBM_PROJECT_v1.MANDATORY (CoCode) VALUES (NEW.CoCode);

END IF;

IF NEW.CoType = 2
	THEN INSERT INTO DBM_PROJECT_v1.OPTIONAL (CoCode) VALUES (NEW.CoCode); 
	INSERT INTO DBM_PROJECT_v1.TECHNICAL (CoCode) VALUES (NEW.CoCode);

END IF;

IF NEW.CoType = 3
	THEN INSERT INTO DBM_PROJECT_v1.OPTIONAL (CoCode) VALUES (NEW.CoCode); 
	INSERT INTO DBM_PROJECT_v1.N_TECHNICAL (CoCode) VALUES (NEW.CoCode);

END IF;

END





CREATE TRIGGER deleteStudent

AFTER DELETE

ON DBM_PROJECT_v1.STUDENT

FOR EACH ROW

BEGIN

DELETE FROM `DBM_PROJECT_v1`.`PERSON` WHERE PERSON.PersonID = (OLD. PersonID);

END










